STOPWORDS = {
    "A", "AS", "O", "OS", "DE", "DA", "DO", "DAS", "DOS", "COM", "PARA", "POR",
    "E", "EM", "NA", "NO", "NAS", "NOS", "UM", "UMA",
}

UNIT_SYNONYMS = {
    "UN": "UN",
    "UND": "UN",
    "UNID": "UN",
    "UNIDADE": "UN",
    "PC": "PC",
    "PCA": "PC",
    "PCE": "PC",
    "PECA": "PC",
    "PEC": "PC",
    "PÇ": "PC",
    "PCT": "PCT",
    "KG": "KG",
    "KG.": "KG",
    "QUILO": "KG",
    "KILO": "KG",
    "G": "G",
    "GR": "G",
    "GRAMA": "G",
    "LT": "LT",
    "L": "LT",
    "LITRO": "LT",
    "ML": "ML",
    "CX": "CX",
    "CAIXA": "CX",
    "FD": "FD",
    "FARDO": "FD",
    "SC": "SC",
    "SACO": "SC",
    "JG": "JG",
    "JOGO": "JG",
    "PAR": "PAR",
}

FINAL_SCHEMA = {
    "descrição_normalizada": "string",
    "descricao": "string",
    "codigo_padrao": "string",
    "lista_codigos": "object",
    "lista_tipo_item": "object",
    "lista_ncm": "object",
    "lista_cest": "object",
    "lista_gtin": "object",
    "lista_unid": "object",
    "tipo_item_padrao": "string",
    "NCM_padrao": "string",
    "CEST_padrao": "string",
    "GTIN_padrao": "string",
    "lista_fontes": "object",
    "lista_descricoes": "object",
    "lista_descricoes_normalizadas": "object",
    "qtd_codigos": "int64",
    "descricao_padrao": "string",
    "verificado": "boolean",
}

CODIGOS_DESAG_SCHEMA = {
    "codigo_desagregado": "string",
    "descricao": "string",
    "lista_tipo_item": "object",
    "lista_ncm": "object",
    "lista_cest": "object",
    "lista_gtin": "object",
    "lista_unid": "object",
    "lista_fontes": "object",
    "lista_descricoes": "object",
    "lista_descricoes_normalizadas": "object",
    "qtd_codigos": "int64",
    "descricao_padrao": "string",
}
